/*
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ElementalRuntimeModule extends AbstractElementalRuntimeModule {
}
