/*
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ElementalStandaloneSetup extends ElementalStandaloneSetupGenerated {

	def static void doSetup() {
		new ElementalStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
