/**
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.elemental;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.benjholla.elemental.elemental.ElementalFactory
 * @model kind="package"
 * @generated
 */
public interface ElementalPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "elemental";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.benjholla.com/elemental/Elemental";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "elemental";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ElementalPackage eINSTANCE = com.benjholla.elemental.elemental.impl.ElementalPackageImpl.init();

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.ProgramImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Implicit Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__IMPLICIT_FUNCTION = 0;

  /**
   * The feature id for the '<em><b>Explicit Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__EXPLICIT_FUNCTIONS = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.BlockImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 1;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__INSTRUCTIONS = 0;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.LabelImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getLabel()
   * @generated
   */
  int LABEL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__NAME = 0;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.FunctionImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__BODY = 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.InstructionImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION__TYPE = 0;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.IncrementImpl <em>Increment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.IncrementImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getIncrement()
   * @generated
   */
  int INCREMENT = 5;

  /**
   * The number of structural features of the '<em>Increment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCREMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.DecrementImpl <em>Decrement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.DecrementImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getDecrement()
   * @generated
   */
  int DECREMENT = 6;

  /**
   * The number of structural features of the '<em>Decrement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECREMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.MoveLeftImpl <em>Move Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.MoveLeftImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getMoveLeft()
   * @generated
   */
  int MOVE_LEFT = 7;

  /**
   * The number of structural features of the '<em>Move Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_LEFT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.MoveRightImpl <em>Move Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.MoveRightImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getMoveRight()
   * @generated
   */
  int MOVE_RIGHT = 8;

  /**
   * The number of structural features of the '<em>Move Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_RIGHT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.StoreImpl <em>Store</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.StoreImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getStore()
   * @generated
   */
  int STORE = 9;

  /**
   * The number of structural features of the '<em>Store</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.RecallImpl <em>Recall</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.RecallImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getRecall()
   * @generated
   */
  int RECALL = 10;

  /**
   * The number of structural features of the '<em>Recall</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECALL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.AssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.AssignmentImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getAssignment()
   * @generated
   */
  int ASSIGNMENT = 11;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.BranchImpl <em>Branch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.BranchImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getBranch()
   * @generated
   */
  int BRANCH = 12;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRANCH__BODY = 0;

  /**
   * The number of structural features of the '<em>Branch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BRANCH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.LoopImpl <em>Loop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.LoopImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getLoop()
   * @generated
   */
  int LOOP = 13;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP__BODY = 0;

  /**
   * The number of structural features of the '<em>Loop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.GOTOImpl <em>GOTO</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.GOTOImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getGOTO()
   * @generated
   */
  int GOTO = 14;

  /**
   * The feature id for the '<em><b>Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO__LABEL = 0;

  /**
   * The number of structural features of the '<em>GOTO</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.ComputedGOTOImpl <em>Computed GOTO</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.ComputedGOTOImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getComputedGOTO()
   * @generated
   */
  int COMPUTED_GOTO = 15;

  /**
   * The number of structural features of the '<em>Computed GOTO</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTED_GOTO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.StaticDispatchImpl <em>Static Dispatch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.StaticDispatchImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getStaticDispatch()
   * @generated
   */
  int STATIC_DISPATCH = 16;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_DISPATCH__TARGET = 0;

  /**
   * The number of structural features of the '<em>Static Dispatch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_DISPATCH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.benjholla.elemental.elemental.impl.DynamicDispatchImpl <em>Dynamic Dispatch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.benjholla.elemental.elemental.impl.DynamicDispatchImpl
   * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getDynamicDispatch()
   * @generated
   */
  int DYNAMIC_DISPATCH = 17;

  /**
   * The number of structural features of the '<em>Dynamic Dispatch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DYNAMIC_DISPATCH_FEATURE_COUNT = 0;


  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see com.benjholla.elemental.elemental.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link com.benjholla.elemental.elemental.Program#getImplicitFunction <em>Implicit Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Implicit Function</em>'.
   * @see com.benjholla.elemental.elemental.Program#getImplicitFunction()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_ImplicitFunction();

  /**
   * Returns the meta object for the containment reference list '{@link com.benjholla.elemental.elemental.Program#getExplicitFunctions <em>Explicit Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Explicit Functions</em>'.
   * @see com.benjholla.elemental.elemental.Program#getExplicitFunctions()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_ExplicitFunctions();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see com.benjholla.elemental.elemental.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for the containment reference list '{@link com.benjholla.elemental.elemental.Block#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see com.benjholla.elemental.elemental.Block#getInstructions()
   * @see #getBlock()
   * @generated
   */
  EReference getBlock_Instructions();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see com.benjholla.elemental.elemental.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for the attribute '{@link com.benjholla.elemental.elemental.Label#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.benjholla.elemental.elemental.Label#getName()
   * @see #getLabel()
   * @generated
   */
  EAttribute getLabel_Name();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see com.benjholla.elemental.elemental.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link com.benjholla.elemental.elemental.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.benjholla.elemental.elemental.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.benjholla.elemental.elemental.Function#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see com.benjholla.elemental.elemental.Function#getBody()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Body();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see com.benjholla.elemental.elemental.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for the containment reference '{@link com.benjholla.elemental.elemental.Instruction#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see com.benjholla.elemental.elemental.Instruction#getType()
   * @see #getInstruction()
   * @generated
   */
  EReference getInstruction_Type();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Increment <em>Increment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Increment</em>'.
   * @see com.benjholla.elemental.elemental.Increment
   * @generated
   */
  EClass getIncrement();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Decrement <em>Decrement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decrement</em>'.
   * @see com.benjholla.elemental.elemental.Decrement
   * @generated
   */
  EClass getDecrement();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.MoveLeft <em>Move Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Left</em>'.
   * @see com.benjholla.elemental.elemental.MoveLeft
   * @generated
   */
  EClass getMoveLeft();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.MoveRight <em>Move Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Right</em>'.
   * @see com.benjholla.elemental.elemental.MoveRight
   * @generated
   */
  EClass getMoveRight();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Store <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store</em>'.
   * @see com.benjholla.elemental.elemental.Store
   * @generated
   */
  EClass getStore();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Recall <em>Recall</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recall</em>'.
   * @see com.benjholla.elemental.elemental.Recall
   * @generated
   */
  EClass getRecall();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Assignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see com.benjholla.elemental.elemental.Assignment
   * @generated
   */
  EClass getAssignment();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Branch <em>Branch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Branch</em>'.
   * @see com.benjholla.elemental.elemental.Branch
   * @generated
   */
  EClass getBranch();

  /**
   * Returns the meta object for the containment reference '{@link com.benjholla.elemental.elemental.Branch#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see com.benjholla.elemental.elemental.Branch#getBody()
   * @see #getBranch()
   * @generated
   */
  EReference getBranch_Body();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.Loop <em>Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop</em>'.
   * @see com.benjholla.elemental.elemental.Loop
   * @generated
   */
  EClass getLoop();

  /**
   * Returns the meta object for the containment reference '{@link com.benjholla.elemental.elemental.Loop#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see com.benjholla.elemental.elemental.Loop#getBody()
   * @see #getLoop()
   * @generated
   */
  EReference getLoop_Body();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.GOTO <em>GOTO</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GOTO</em>'.
   * @see com.benjholla.elemental.elemental.GOTO
   * @generated
   */
  EClass getGOTO();

  /**
   * Returns the meta object for the reference '{@link com.benjholla.elemental.elemental.GOTO#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Label</em>'.
   * @see com.benjholla.elemental.elemental.GOTO#getLabel()
   * @see #getGOTO()
   * @generated
   */
  EReference getGOTO_Label();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.ComputedGOTO <em>Computed GOTO</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Computed GOTO</em>'.
   * @see com.benjholla.elemental.elemental.ComputedGOTO
   * @generated
   */
  EClass getComputedGOTO();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.StaticDispatch <em>Static Dispatch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Static Dispatch</em>'.
   * @see com.benjholla.elemental.elemental.StaticDispatch
   * @generated
   */
  EClass getStaticDispatch();

  /**
   * Returns the meta object for the reference '{@link com.benjholla.elemental.elemental.StaticDispatch#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see com.benjholla.elemental.elemental.StaticDispatch#getTarget()
   * @see #getStaticDispatch()
   * @generated
   */
  EReference getStaticDispatch_Target();

  /**
   * Returns the meta object for class '{@link com.benjholla.elemental.elemental.DynamicDispatch <em>Dynamic Dispatch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dynamic Dispatch</em>'.
   * @see com.benjholla.elemental.elemental.DynamicDispatch
   * @generated
   */
  EClass getDynamicDispatch();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ElementalFactory getElementalFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.ProgramImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Implicit Function</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__IMPLICIT_FUNCTION = eINSTANCE.getProgram_ImplicitFunction();

    /**
     * The meta object literal for the '<em><b>Explicit Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__EXPLICIT_FUNCTIONS = eINSTANCE.getProgram_ExplicitFunctions();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.BlockImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__INSTRUCTIONS = eINSTANCE.getBlock_Instructions();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.LabelImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__NAME = eINSTANCE.getLabel_Name();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.FunctionImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__BODY = eINSTANCE.getFunction_Body();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.InstructionImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCTION__TYPE = eINSTANCE.getInstruction_Type();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.IncrementImpl <em>Increment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.IncrementImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getIncrement()
     * @generated
     */
    EClass INCREMENT = eINSTANCE.getIncrement();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.DecrementImpl <em>Decrement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.DecrementImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getDecrement()
     * @generated
     */
    EClass DECREMENT = eINSTANCE.getDecrement();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.MoveLeftImpl <em>Move Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.MoveLeftImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getMoveLeft()
     * @generated
     */
    EClass MOVE_LEFT = eINSTANCE.getMoveLeft();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.MoveRightImpl <em>Move Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.MoveRightImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getMoveRight()
     * @generated
     */
    EClass MOVE_RIGHT = eINSTANCE.getMoveRight();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.StoreImpl <em>Store</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.StoreImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getStore()
     * @generated
     */
    EClass STORE = eINSTANCE.getStore();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.RecallImpl <em>Recall</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.RecallImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getRecall()
     * @generated
     */
    EClass RECALL = eINSTANCE.getRecall();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.AssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.AssignmentImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getAssignment()
     * @generated
     */
    EClass ASSIGNMENT = eINSTANCE.getAssignment();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.BranchImpl <em>Branch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.BranchImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getBranch()
     * @generated
     */
    EClass BRANCH = eINSTANCE.getBranch();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BRANCH__BODY = eINSTANCE.getBranch_Body();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.LoopImpl <em>Loop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.LoopImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getLoop()
     * @generated
     */
    EClass LOOP = eINSTANCE.getLoop();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP__BODY = eINSTANCE.getLoop_Body();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.GOTOImpl <em>GOTO</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.GOTOImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getGOTO()
     * @generated
     */
    EClass GOTO = eINSTANCE.getGOTO();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOTO__LABEL = eINSTANCE.getGOTO_Label();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.ComputedGOTOImpl <em>Computed GOTO</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.ComputedGOTOImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getComputedGOTO()
     * @generated
     */
    EClass COMPUTED_GOTO = eINSTANCE.getComputedGOTO();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.StaticDispatchImpl <em>Static Dispatch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.StaticDispatchImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getStaticDispatch()
     * @generated
     */
    EClass STATIC_DISPATCH = eINSTANCE.getStaticDispatch();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATIC_DISPATCH__TARGET = eINSTANCE.getStaticDispatch_Target();

    /**
     * The meta object literal for the '{@link com.benjholla.elemental.elemental.impl.DynamicDispatchImpl <em>Dynamic Dispatch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.benjholla.elemental.elemental.impl.DynamicDispatchImpl
     * @see com.benjholla.elemental.elemental.impl.ElementalPackageImpl#getDynamicDispatch()
     * @generated
     */
    EClass DYNAMIC_DISPATCH = eINSTANCE.getDynamicDispatch();

  }

} //ElementalPackage
