/**
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.elemental;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Increment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.benjholla.elemental.elemental.ElementalPackage#getIncrement()
 * @model
 * @generated
 */
public interface Increment extends EObject
{
} // Increment
