/**
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.elemental;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.benjholla.elemental.elemental.Program#getImplicitFunction <em>Implicit Function</em>}</li>
 *   <li>{@link com.benjholla.elemental.elemental.Program#getExplicitFunctions <em>Explicit Functions</em>}</li>
 * </ul>
 *
 * @see com.benjholla.elemental.elemental.ElementalPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Implicit Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Implicit Function</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Implicit Function</em>' containment reference.
   * @see #setImplicitFunction(Block)
   * @see com.benjholla.elemental.elemental.ElementalPackage#getProgram_ImplicitFunction()
   * @model containment="true"
   * @generated
   */
  Block getImplicitFunction();

  /**
   * Sets the value of the '{@link com.benjholla.elemental.elemental.Program#getImplicitFunction <em>Implicit Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Implicit Function</em>' containment reference.
   * @see #getImplicitFunction()
   * @generated
   */
  void setImplicitFunction(Block value);

  /**
   * Returns the value of the '<em><b>Explicit Functions</b></em>' containment reference list.
   * The list contents are of type {@link com.benjholla.elemental.elemental.Function}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Explicit Functions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Explicit Functions</em>' containment reference list.
   * @see com.benjholla.elemental.elemental.ElementalPackage#getProgram_ExplicitFunctions()
   * @model containment="true"
   * @generated
   */
  EList<Function> getExplicitFunctions();

} // Program
