/*
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.ui;

import com.benjholla.elemental.ui.internal.ElementalActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ElementalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ElementalActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ElementalActivator activator = ElementalActivator.getInstance();
		return activator != null ? activator.getInjector(ElementalActivator.COM_BENJHOLLA_ELEMENTAL_ELEMENTAL) : null;
	}

}
