/*
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractElementalScopeProvider extends DelegatingScopeProvider {
}
