/*
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.ui.tests;

import com.benjholla.elemental.ui.internal.ElementalActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ElementalUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ElementalActivator.getInstance().getInjector("com.benjholla.elemental.Elemental");
	}

}
