/*
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.ide


/**
 * Use this class to register ide components.
 */
class ElementalIdeModule extends AbstractElementalIdeModule {
}
