/**
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.elemental.impl;

import com.benjholla.elemental.elemental.ComputedGOTO;
import com.benjholla.elemental.elemental.ElementalPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Computed GOTO</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComputedGOTOImpl extends MinimalEObjectImpl.Container implements ComputedGOTO
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComputedGOTOImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ElementalPackage.Literals.COMPUTED_GOTO;
  }

} //ComputedGOTOImpl
