/**
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.elemental.impl;

import com.benjholla.elemental.elemental.DynamicDispatch;
import com.benjholla.elemental.elemental.ElementalPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dynamic Dispatch</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DynamicDispatchImpl extends MinimalEObjectImpl.Container implements DynamicDispatch
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DynamicDispatchImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ElementalPackage.Literals.DYNAMIC_DISPATCH;
  }

} //DynamicDispatchImpl
