/**
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.elemental.impl;

import com.benjholla.elemental.elemental.ElementalPackage;
import com.benjholla.elemental.elemental.MoveLeft;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Move Left</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MoveLeftImpl extends MinimalEObjectImpl.Container implements MoveLeft
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MoveLeftImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ElementalPackage.Literals.MOVE_LEFT;
  }

} //MoveLeftImpl
