/*
 * generated by Xtext 2.16.0
 */
package com.benjholla.elemental.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ElementalAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/benjholla/elemental/parser/antlr/internal/InternalElemental.tokens");
	}
}
